version: '3.7'
services:
  api:
    container_name: portfolios_api
    build: .
    tty: true
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - type: bind
        source: .
        target: /portfolios
    depends_on:
      - db
  db:
    image: mysql
    restart: always
    container_name: portfolios_db
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: portfolios
      MYSQL_USER: user
      MYSQL_PASSWORD: password 